#FROM registry.access.redhat.com/ubi8/python-39
FROM quay.io/sclorg/python-39-minimal

USER 0
ADD loadtest.py requirements.txt .
RUN chown -R 1001:0 ./
USER 1001

RUN pip install -U "pip>=19.3.1" && \
    pip install -r requirements.txt

CMD python loadtest.py
